# Generated by Django 5.1.7 on 2025-03-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_property_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
