# Generated by Django 5.1.7 on 2025-03-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_remove_property_image_property_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='images',
        ),
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
