# Generated by Django 5.1.7 on 2025-03-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_remove_property_images_property_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='image',
        ),
        migrations.AddField(
            model_name='property',
            name='images',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
