# Generated by Django 5.1.7 on 2025-03-27 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_alter_property_latitude_alter_property_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='property',
            name='longitude',
        ),
    ]
