# Generated by Django 5.1.7 on 2025-03-25 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
        ('properties', '0004_alter_property_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together={('buyer', 'seller')},
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatrooms', to='properties.property'),
        ),
    ]
